import { expect, it, vi } from 'vitest'
import { fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import PdfStudyTools from './PdfStudyTools'
import { readStudyNotes, writeStudyNotes } from '../../services/document.service'
vi.mock('../../services/document.service', () => ({ readStudyNotes: vi.fn(), writeStudyNotes: vi.fn(async () => {}) }))
function open() {
  return render(<PdfStudyTools enabled documentId="d" versionId="v" pageNumber={1} ratio={1.5} ready readerRef={{ current: null }}>{({ toolbar, overlay, notes }) => <>{toolbar}{overlay}{notes}</>}</PdfStudyTools>)
}
it('hides feedback for teachers while retaining the annotation tools and notes', async () => {
  readStudyNotes.mockResolvedValue({ items: [], notes: '' })
  render(<PdfStudyTools enabled showFeedback={false} documentId="d" versionId="v" pageNumber={1} ready readerRef={{ current: null }}>{({ toolbar, notes }) => <>{toolbar}{notes}</>}</PdfStudyTools>)
  await waitFor(() => expect(screen.getByRole('button', { name: 'Bút viết tay' })).toBeEnabled())
  expect(screen.queryByText('Nội dung này có hữu ích không?')).not.toBeInTheDocument()
  expect(screen.queryByRole('button', { name: 'Like' })).not.toBeInTheDocument()
  expect(screen.queryByRole('button', { name: 'Báo cáo bài học' })).not.toBeInTheDocument()
  await userEvent.click(screen.getByRole('button', { name: 'Ghi chú', exact: true }))
  expect(screen.getByLabelText('Ghi chú của tôi')).toBeVisible()
})
it('keeps the requested tool order and restores personal marks after re-entering', async () => {
  readStudyNotes.mockResolvedValue({ items: [{ id: 'a', page: 1, kind: 'text', x: 0.2, y: 0.3, text: 'Saved text' }], notes: 'Saved note' })
  const view = open()
  expect(await screen.findByText('Saved text')).toBeInTheDocument()
  const tools = within(screen.getByRole('toolbar', { name: 'Công cụ học tập' })).getAllByRole('button').map((button) => button.getAttribute('aria-label'))
  expect(tools).toEqual(['Con trỏ', 'Bút viết tay', 'Tô highlight', 'Tẩy', 'Viết text', 'Undo', 'Xóa toàn bộ', 'Toàn màn hình', 'Ghi chú'])
  await userEvent.click(screen.getByRole('button', { name: 'Ghi chú', exact: true }))
  expect(screen.getByLabelText('Ghi chú của tôi')).toHaveValue('Saved note')
  await userEvent.type(screen.getByLabelText('Ghi chú của tôi'), '!')
  await waitFor(() => expect(writeStudyNotes).toHaveBeenLastCalledWith('d', 'v', expect.objectContaining({ notes: 'Saved note!' })))
  view.unmount()
  open()
  expect(await screen.findByText('Saved text')).toBeInTheDocument()
})
it('requires confirmation before clearing marks and supports undo', async () => {
  readStudyNotes.mockResolvedValue({ items: [{ id: 'a', page: 1, kind: 'text', x: 0.2, y: 0.3, text: 'Keep me' }], notes: 'Keep notes' })
  open()
  await screen.findByText('Keep me')
  await userEvent.click(screen.getByRole('button', { name: 'Xóa toàn bộ', exact: true }))
  expect(screen.getByRole('dialog')).toBeVisible()
  await userEvent.click(screen.getByRole('button', { name: 'Hủy' }))
  expect(screen.getByText('Keep me')).toBeInTheDocument()
  await userEvent.click(screen.getByRole('button', { name: 'Xóa toàn bộ', exact: true }))
  await userEvent.click(screen.getByRole('button', { name: 'Xác nhận xóa' }))
  expect(screen.queryByText('Keep me')).not.toBeInTheDocument()
  await userEvent.click(screen.getByRole('button', { name: 'Undo' }))
  expect(screen.getByText('Keep me')).toBeInTheDocument()
})
it('saves normalized pen and highlight coordinates, adds text and erases a selected mark', async () => {
  vi.stubGlobal('PointerEvent', MouseEvent)
  readStudyNotes.mockResolvedValue({ items: [], notes: '' })
  open()
  await waitFor(() => expect(screen.getByRole('button', { name: 'Bút viết tay' })).toBeEnabled())
  const svg = screen.getByLabelText('Lớp ghi chú trên tài liệu')
  vi.spyOn(svg, 'getBoundingClientRect').mockReturnValue({ left: 0, top: 0, width: 1000, height: 1500 })
  await userEvent.click(screen.getByRole('button', { name: 'Bút viết tay' }))
  fireEvent.pointerDown(svg, { button: 0, clientX: 100, clientY: 300 })
  fireEvent.pointerMove(svg, { clientX: 200, clientY: 450 })
  fireEvent.pointerUp(svg)
  expect(writeStudyNotes).toHaveBeenLastCalledWith('d', 'v', expect.objectContaining({ items: [expect.objectContaining({ kind: 'pen', page: 1, points: [[0.1, 0.2], [0.2, 0.3]] })] }))
  await userEvent.click(screen.getByRole('button', { name: 'Tô highlight' }))
  fireEvent.pointerDown(svg, { button: 0, clientX: 100, clientY: 100 })
  fireEvent.pointerMove(svg, { clientX: 500, clientY: 100 })
  fireEvent.pointerUp(svg)
  expect(writeStudyNotes.mock.calls.at(-1)[2].items[1].kind).toBe('highlight')
  await userEvent.click(screen.getByRole('button', { name: 'Viết text' }))
  fireEvent.pointerDown(svg, { button: 0, clientX: 300, clientY: 600 })
  await userEvent.type(screen.getByLabelText('Text trên tài liệu'), 'My text')
  await userEvent.click(screen.getByRole('button', { name: 'Thêm text' }))
  expect(screen.getByText('My text', { selector: 'text' })).toBeInTheDocument()
  await userEvent.click(screen.getByRole('button', { name: 'Tẩy', exact: true }))
  fireEvent.pointerDown(screen.getByText('My text', { selector: 'text' }), { button: 0, clientX: 300, clientY: 600 })
  expect(screen.queryByText('My text', { selector: 'text' })).not.toBeInTheDocument()
  vi.unstubAllGlobals()
})
it('replaces the save caption with voting and a report dialog that sends reason and opinion', async () => {
  readStudyNotes.mockResolvedValue({ items: [], notes: '' })
  writeStudyNotes.mockClear()
  open()
  await waitFor(() => expect(screen.getByRole('button', { name: 'Like' })).toBeEnabled())
  expect(screen.queryByText('Đã lưu trong phiên làm việc')).not.toBeInTheDocument()
  expect(screen.getByText('Nội dung này có hữu ích không?')).toBeVisible()
  await userEvent.click(screen.getByRole('button', { name: 'Like' }))
  expect(screen.getByRole('button', { name: 'Like' })).toHaveAttribute('aria-pressed', 'true')
  await userEvent.click(screen.getByRole('button', { name: 'Unlike' }))
  expect(screen.getByRole('button', { name: 'Like' })).toHaveAttribute('aria-pressed', 'false')
  const calls = writeStudyNotes.mock.calls.length
  await userEvent.click(screen.getByRole('button', { name: 'Báo cáo bài học' }))
  expect(screen.getByRole('dialog', { name: 'Báo cáo bài học' })).toBeVisible()
  await userEvent.click(screen.getByRole('button', { name: 'Hủy', exact: true }))
  expect(writeStudyNotes).toHaveBeenCalledTimes(calls)
  await userEvent.click(screen.getByRole('button', { name: 'Báo cáo bài học' }))
  await userEvent.type(screen.getByLabelText('Lý do'), 'Nội dung sai')
  await userEvent.type(screen.getByLabelText('Ý kiến của bạn'), 'Vui lòng kiểm tra trang 1')
  await userEvent.click(screen.getByRole('button', { name: 'Gửi', exact: true }))
  await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
  expect(writeStudyNotes).toHaveBeenLastCalledWith('d', 'v', expect.objectContaining({ feedback: { vote: 'dislike', report: { reason: 'Nội dung sai', opinion: 'Vui lòng kiểm tra trang 1' } } }))
})
it('retains report fields when sending fails and permits retry', async () => {
  readStudyNotes.mockResolvedValue({ items: [], notes: '' })
  open()
  await waitFor(() => expect(screen.getByRole('button', { name: 'Báo cáo bài học' })).toBeEnabled())
  await userEvent.click(screen.getByRole('button', { name: 'Báo cáo bài học' }))
  await userEvent.type(screen.getByLabelText('Lý do'), 'Trang bị lỗi')
  writeStudyNotes.mockRejectedValueOnce(new Error('Offline'))
  await userEvent.click(screen.getByRole('button', { name: 'Gửi', exact: true }))
  expect(await screen.findByRole('alert')).toHaveTextContent('Không thể gửi báo cáo')
  expect(screen.getByLabelText('Lý do')).toHaveValue('Trang bị lỗi')
  await userEvent.click(screen.getByRole('button', { name: 'Gửi', exact: true }))
  await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
})
