import { beforeEach, expect, it, vi } from 'vitest'
import { render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import ClassroomWorkspace from './ClassroomWorkspace'
import { createClassroomSession, createClassroomAnnouncement, listClassroomSessions, deleteClassroomSession } from '../services/course.service'
vi.mock('../services/course.service', async (original) => ({ ...await original(), deleteClassroomSession: vi.fn(async () => undefined), listClassroomSessions: vi.fn(async () => []), listClassroomAnnouncements: vi.fn(async () => []), createClassroomSession: vi.fn(async () => ({ id: 's1', title: '', position: 1, material_count: 0 })), createClassroomAnnouncement: vi.fn(async (_, __, values) => ({ id: 'a1', ...values, author_name: 'Giáo viên', created_at: '2026-10-09T08:00:00Z' })) }))
vi.mock('./documents/CourseDocuments', () => ({ default: () => <div>Học liệu buổi học</div> }))
beforeEach(() => vi.clearAllMocks())
const open = () => render(<ClassroomWorkspace course={{ id: 'c1', title: 'Python' }} initialRoom={{ id: 'r1', name: 'Lớp sáng', class_code: 'ABC', enrolled_count: 0 }} />)
it('confirms deleting a session without opening it and removes its card after success', async () => {
  listClassroomSessions.mockResolvedValueOnce([{id:'s1',title:'Buổi cần xóa',material_count:2}])
  open()
  await userEvent.click(screen.getByRole('button',{name:'Buổi học',exact:true}))
  await userEvent.click(await screen.findByRole('button',{name:'Xóa buổi học Buổi cần xóa'}))
  expect(screen.getByRole('dialog',{name:'Xóa buổi học?'})).toBeVisible()
  expect(screen.queryByRole('region',{name:'Chi tiết buổi học'})).not.toBeInTheDocument()
  expect(deleteClassroomSession).not.toHaveBeenCalled()
  await userEvent.click(screen.getByRole('button',{name:'Xác nhận xóa'}))
  expect(deleteClassroomSession).toHaveBeenCalledWith('c1','r1','s1')
  expect(screen.queryByRole('button',{name:/Buổi cần xóa/})).not.toBeInTheDocument()
})
it('labels only draft sessions in the classroom list', async () => {
  listClassroomSessions.mockResolvedValueOnce([{ id:'s1',title:'Draft session',is_draft:true,material_count:0 },{ id:'s2',title:'Created session',is_draft:false,material_count:0 }])
  open()
  await userEvent.click(screen.getByRole('button',{name:'Buổi học',exact:true}))
  expect(await screen.findByRole('button',{name:/Draft session.*Bản nháp/})).toBeVisible()
  expect(screen.getByRole('button',{name:/^Created session/})).not.toHaveTextContent('Bản nháp')
})
it('creates a blank clickable session and restricts AI to the opened session', async () => {
  open()
  expect(screen.queryByRole('button', { name: 'Trợ lý AI' })).not.toBeInTheDocument()
  await userEvent.click(screen.getByRole('button', { name: 'Buổi học', exact: true }))
  await userEvent.click(screen.getByRole('button', { name: 'Thêm mới', exact: true }))
  expect(createClassroomSession).toHaveBeenCalledWith('c1', 'r1', {})
  expect(screen.queryByRole('button', { name: 'Trợ lý AI' })).not.toBeInTheDocument()
  await userEvent.click(await screen.findByRole('button', { name: /^Buổi học chưa đặt tên/ }))
  await userEvent.click(screen.getByRole('button', { name: 'Trợ lý AI' }))
  expect(screen.getByRole('complementary', { name: 'Trợ lý AI của buổi học' })).toBeVisible()
  await userEvent.click(screen.getByRole('button', { name: 'Các buổi học', exact: true }))
  expect(screen.queryByRole('complementary')).not.toBeInTheDocument()
  expect(screen.queryByRole('button', { name: 'Trợ lý AI' })).not.toBeInTheDocument()
})
it('posts an announcement and retains the draft after failure', async () => {
  createClassroomAnnouncement.mockRejectedValueOnce(new Error('Offline'))
  open()
  await userEvent.click(screen.getByRole('button', { name: 'Thêm mới', exact: true }))
  await userEvent.type(screen.getByLabelText('Nội dung thông báo'), 'Thông báo học ngày mai')
  await userEvent.click(screen.getByRole('button', { name: 'Đăng thông báo' }))
  expect(await screen.findByRole('alert')).toBeVisible()
  expect(screen.getByLabelText('Nội dung thông báo')).toHaveValue('Thông báo học ngày mai')
  await userEvent.click(screen.getByRole('button', { name: 'Đăng thông báo' }))
  expect(await screen.findByText('Thông báo học ngày mai')).toBeVisible()
  expect(createClassroomAnnouncement).toHaveBeenLastCalledWith('c1', 'r1', { content: 'Thông báo học ngày mai' })
  expect(screen.queryByLabelText('Nội dung thông báo')).not.toBeInTheDocument()
})

it('prevents session creation during a pending reload after leaving details', async () => {
  listClassroomSessions.mockResolvedValueOnce([{ id: 's1', title: 'Buổi 1', material_count: 0 }])
  let finishReload
  listClassroomSessions.mockImplementationOnce(() => new Promise((resolve) => { finishReload = resolve }))
  open()
  await userEvent.click(screen.getByRole('button', { name: 'Buổi học', exact: true }))
  await userEvent.click(await screen.findByRole('button', { name: /^Buổi 1/ }))
  await userEvent.click(screen.getByRole('button', { name: 'Các buổi học', exact: true }))
  expect(screen.getByRole('button', { name: 'Thêm mới' })).toBeDisabled()
  await userEvent.click(screen.getByRole('button', { name: 'Thêm mới' }))
  expect(createClassroomSession).not.toHaveBeenCalled()
  finishReload([{ id: 's1', title: 'Buổi 1', material_count: 0 }])
  await screen.findByRole('button', { name: /^Buổi 1/ })
  expect(screen.getByRole('button', { name: 'Thêm mới' })).toBeEnabled()
})

it('attaches an image and link to the announcement draft', async () => {
  open()
  await userEvent.click(await screen.findByRole('button', { name: 'Thêm mới' }))
  await userEvent.type(screen.getByLabelText('Nội dung thông báo'), 'Xem ảnh và tài liệu')
  await userEvent.type(screen.getByLabelText('Đường link'), 'https://example.com/lesson')
  const image = new File(['image'], 'lesson.png', { type: 'image/png' })
  await userEvent.upload(screen.getByLabelText('Ảnh đính kèm'), image)
  expect(await screen.findByRole('img', { name: 'Xem trước ảnh đính kèm' })).toBeVisible()
  await userEvent.click(screen.getByRole('button', { name: 'Đăng thông báo' }))
  expect(createClassroomAnnouncement).toHaveBeenLastCalledWith('c1', 'r1', { content: 'Xem ảnh và tài liệu', link: 'https://example.com/lesson', image })
  expect(await screen.findByRole('link', { name: /example.com/ })).toHaveAttribute('href', 'https://example.com/lesson')
})
