import { beforeEach, describe, expect, it, vi } from 'vitest'
import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { StudentEnrollmentPanel, TeacherEnrollmentPanel } from './EnrollmentPanels'
import * as service from '../services/course.service'

vi.mock('../services/course.service', async (original) => ({
  ...await original(),
  getAccessPolicy: vi.fn(), listClassrooms: vi.fn(), listJoinRequests: vi.fn(),
  updateAccessPolicy: vi.fn(), createClassroom: vi.fn(), updateClassroom: vi.fn(),
  reviewJoinRequest: vi.fn(), listMyJoinRequests: vi.fn(), listMyEnrollments: vi.fn(),
  joinClassroom: vi.fn(), cancelJoinRequest: vi.fn(),
  listClassroomEnrollments: vi.fn(), revokeClassroomEnrollment: vi.fn(),
}))
const request = { id: 'r1', course_title: 'Python', classroom_name: 'Lớp tối', status: 'PENDING', created_at: '2026-10-08T10:00:00Z', message: 'Xin tham gia', student: { full_name: 'Minh Anh', email: 'anh@example.com' } }
const course = { id: 'c1', status: 'PUBLISHED' }
describe('enrollment workflows', () => {
  beforeEach(() => {
    vi.resetAllMocks()
    service.getAccessPolicy.mockResolvedValue({ require_approval: false, visibility: 'PRIVATE' })
    service.listClassrooms.mockResolvedValue([{ id: 'room1', name: 'Lớp tối', class_code: 'A1B2C3D4E5F6', is_join_enabled: true }])
    service.listJoinRequests.mockResolvedValue([request])
    service.listMyJoinRequests.mockResolvedValue([request])
    service.listMyEnrollments.mockResolvedValue([])
    service.listClassroomEnrollments.mockResolvedValue([])
  })
  it.each(['ENROLLED', 'PENDING'])('joins a class and refreshes courses: %s', async (status) => {
    service.joinClassroom.mockResolvedValue({ status })
    const refresh = vi.fn().mockResolvedValue(undefined)
    render(<StudentEnrollmentPanel onCoursesChanged={refresh} />)
    await screen.findByText('Xin tham gia')
    expect(screen.getByRole('button', { name: 'Tham gia lớp' })).toBeDisabled()
    await userEvent.type(screen.getByLabelText('Mã lớp học'), 'a1b2c3d4e5f6')
    await userEvent.click(screen.getByRole('button', { name: 'Tham gia lớp' }))
    expect(service.joinClassroom).toHaveBeenCalledWith({ class_code: 'A1B2C3D4E5F6', message: '' })
    await waitFor(() => expect(refresh).toHaveBeenCalled())
    expect(screen.getByRole('status')).toHaveTextContent(status === 'PENDING' ? 'đang chờ' : 'thành công')
  })
  it('shows invalid code errors without claiming success', async () => {
    service.joinClassroom.mockRejectedValue({ status: 400, data: { class_code: ['Invalid class code.'] } })
    render(<StudentEnrollmentPanel onCoursesChanged={vi.fn()} />)
    await userEvent.type(screen.getByLabelText('Mã lớp học'), 'FFFFFFFFFFFF')
    await userEvent.click(screen.getByRole('button', { name: 'Tham gia lớp' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('Mã lớp không đúng')
    expect(screen.queryByRole('status')).not.toBeInTheDocument()
  })
  it('cancels a pending request and displays the updated state', async () => {
    service.cancelJoinRequest.mockResolvedValue({ ...request, status: 'CANCELED' })
    render(<StudentEnrollmentPanel onCoursesChanged={vi.fn()} />)
    await screen.findByText('Xin tham gia')
    service.listMyJoinRequests.mockResolvedValue([{ ...request, status: 'CANCELED' }])
    await userEvent.click(screen.getByRole('button', { name: 'Hủy yêu cầu' }))
    expect(service.cancelJoinRequest).not.toHaveBeenCalled()
    await userEvent.click(screen.getByRole('button', { name: 'Xác nhận hủy' }))
    expect(await screen.findByText('Đã hủy yêu cầu tham gia.')).toBeVisible()
    await userEvent.click(screen.getByRole('tab', { name: /Lịch sử yêu cầu/ }))
    expect(await screen.findByText('Đã hủy', { selector: 'span' })).toBeVisible()
    expect(service.cancelJoinRequest).toHaveBeenCalledWith('r1')
    expect(screen.queryByRole('button', { name: 'Hủy yêu cầu' })).not.toBeInTheDocument()
  })
  it('retains the successful join result if refreshing courses fails', async () => {
    service.joinClassroom.mockResolvedValue({ status: 'ENROLLED' })
    render(<StudentEnrollmentPanel onCoursesChanged={vi.fn().mockRejectedValue({ status: 0 })} />)
    await userEvent.type(screen.getByLabelText('Mã lớp học'), 'A1B2C3D4E5F6')
    await userEvent.click(screen.getByRole('button', { name: 'Tham gia lớp' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('Thao tác đã thành công')
    expect(screen.getByRole('status')).toHaveTextContent('tham gia lớp học thành công')
    expect(service.joinClassroom).toHaveBeenCalledTimes(1)
  })
  it('lets the student retry loading history after a connection failure', async () => {
    service.listMyJoinRequests.mockRejectedValueOnce({ status: 0 })
    render(<StudentEnrollmentPanel onCoursesChanged={vi.fn()} />)
    expect(await screen.findByRole('alert')).toHaveTextContent('Không thể kết nối')
    await userEvent.click(screen.getByRole('button', { name: 'Làm mới yêu cầu của tôi' }))
    expect(await screen.findByText('Lớp tối')).toBeVisible()
  })
  it('keeps the review form open when a processed request is rejected', async () => {
    service.reviewJoinRequest.mockRejectedValue({ status: 400, data: { status: ['This request has already been processed.'] } })
    render(<TeacherEnrollmentPanel course={course} requestsOnly onMembersChanged={vi.fn()} />)
    await userEvent.click(await screen.findByRole('button', { name: 'Chấp nhận' }))
    await userEvent.click(screen.getByRole('button', { name: 'Xác nhận' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('Yêu cầu đã được xử lý')
    expect(screen.getByLabelText('Ghi chú phản hồi')).toBeVisible()
    expect(screen.queryByRole('status')).not.toBeInTheDocument()
  })
  it('separates pending requests from history and supports keyboard tabs', async () => {
    service.listMyJoinRequests.mockResolvedValue([request, { ...request, id: 'r2', classroom_name: 'Lớp sáng', status: 'APPROVED' }])
    render(<StudentEnrollmentPanel />)
    expect(await screen.findByText('Lớp tối')).toBeVisible()
    expect(screen.queryByText('Lớp sáng')).not.toBeInTheDocument()
    const pendingTab = screen.getByRole('tab', { name: /Chờ duyệt/ })
    pendingTab.focus()
    await userEvent.keyboard('{End}')
    expect(screen.getByRole('tab', { name: /Lịch sử yêu cầu/ })).toHaveFocus()
    expect(screen.getByText('Lớp sáng')).toBeVisible()
    await userEvent.click(screen.getByRole('combobox', { name: 'Lọc trạng thái' }))
    await userEvent.click(screen.getByRole('option', { name: 'Đã chấp nhận' }))
    expect(screen.queryByText('Lớp tối')).not.toBeInTheDocument()
    expect(screen.getByText('Lớp sáng')).toBeVisible()
  })
  it('defaults to enrolled classes when none are pending and opens the course', async () => {
    service.listMyJoinRequests.mockResolvedValue([])
    service.listMyEnrollments.mockResolvedValue([{ id: 'e1', course_id: 'c1', course_title: 'Python', classroom_name: 'Lớp sáng', status: 'ACTIVE', progress_percent: 15, enrolled_at: request.created_at }])
    const open = vi.fn()
    render(<StudentEnrollmentPanel onOpenCourse={open} />)
    expect(await screen.findByText('Lớp sáng')).toBeVisible()
    expect(screen.getByRole('tab', { name: /Lớp đã tham gia/ })).toHaveAttribute('aria-selected', 'true')
    expect(screen.getByText('15%')).toBeVisible()
    await userEvent.click(screen.getByRole('button', { name: 'Mở khóa học' }))
    expect(open).toHaveBeenCalledWith('c1')
  })
  it('paginates long lists and resets pagination when searching', async () => {
    service.listMyJoinRequests.mockResolvedValue(Array.from({ length: 12 }, (_, i) => ({ ...request, id: `r${i}`, classroom_name: `Lớp số ${i + 1}` })))
    render(<StudentEnrollmentPanel />)
    await screen.findByText('Lớp số 1')
    expect(screen.getAllByRole('article')).toHaveLength(5)
    expect(screen.getByRole('button', { name: 'Trang trước' })).toBeDisabled()
    await userEvent.click(screen.getByRole('button', { name: 'Trang sau' }))
    expect(screen.getByText('Lớp số 6')).toBeVisible()
    await userEvent.type(screen.getByLabelText('Tìm lớp hoặc khóa học'), 'Lớp số 12')
    expect(screen.getAllByRole('article')).toHaveLength(1)
    expect(screen.getByText('Lớp số 12')).toBeVisible()
    expect(screen.queryByRole('button', { name: 'Trang sau' })).not.toBeInTheDocument()
  })
  it('normalizes pasted codes and sends an optional message', async () => {
    service.joinClassroom.mockResolvedValue({ status: 'PENDING' })
    render(<StudentEnrollmentPanel />)
    await screen.findByText('Lớp tối')
    await userEvent.click(screen.getByLabelText('Mã lớp học'))
    await userEvent.paste(' a1b2 c3d4 e5f6 ')
    expect(screen.getByLabelText('Mã lớp học')).toHaveValue('A1B2C3D4E5F6')
    await userEvent.click(screen.getByText(/Lời nhắn cho giáo viên/, { selector: 'summary' }))
    await userEvent.type(screen.getByLabelText('Lời nhắn cho giáo viên'), 'Em muốn tham gia lớp')
    await userEvent.click(screen.getByRole('button', { name: 'Tham gia lớp' }))
    await waitFor(() => expect(service.joinClassroom).toHaveBeenCalledWith({ class_code: 'A1B2C3D4E5F6', message: 'Em muốn tham gia lớp' }))
  })
  it('keeps the request when cancellation is dismissed', async () => {
    render(<StudentEnrollmentPanel />)
    await userEvent.click(await screen.findByRole('button', { name: 'Hủy yêu cầu' }))
    await userEvent.click(screen.getByRole('button', { name: 'Giữ yêu cầu' }))
    expect(screen.queryByRole('button', { name: 'Xác nhận hủy' })).not.toBeInTheDocument()
    expect(service.cancelJoinRequest).not.toHaveBeenCalled()
    expect(screen.getByText('Lớp tối')).toBeVisible()
  })
  it('does not claim a successful refresh on network failure', async () => {
    render(<StudentEnrollmentPanel />)
    await screen.findByText('Lớp tối')
    service.listMyJoinRequests.mockRejectedValue({ status: 0 })
    await userEvent.click(screen.getByRole('button', { name: 'Làm mới yêu cầu của tôi' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('Không thể kết nối')
    expect(screen.queryByRole('status')).not.toBeInTheDocument()
    expect(screen.getByText('Lớp tối')).toBeVisible()
  })
  it.each([['Chấp nhận', 'approve'], ['Từ chối', 'reject']])('reviews requests: %s', async (label, decision) => {
    const refresh = vi.fn()
    render(<TeacherEnrollmentPanel course={course} requestsOnly onMembersChanged={refresh} />)
    await userEvent.click(await screen.findByRole('button', { name: label }))
    await userEvent.type(screen.getByLabelText('Ghi chú phản hồi'), 'Đã kiểm tra')
    await userEvent.click(screen.getByRole('button', { name: 'Xác nhận' }))
    expect(service.reviewJoinRequest).toHaveBeenCalledWith('c1', 'r1', { decision, review_note: 'Đã kiểm tra' })
    await waitFor(() => expect(refresh).toHaveBeenCalled())
  })
  it('updates approval policy, creates classes and closes registration', async () => {
    render(<TeacherEnrollmentPanel course={course} onMembersChanged={vi.fn()} />)
    await userEvent.click(await screen.findByLabelText('Yêu cầu giáo viên xét duyệt'))
    await userEvent.click(screen.getByRole('button', { name: 'Lưu chính sách' }))
    await waitFor(() => expect(service.updateAccessPolicy).toHaveBeenCalledWith('c1', { require_approval: true, visibility: 'PRIVATE' }))
    await userEvent.type(screen.getByLabelText('Tên lớp mới'), 'Lớp sáng')
    await userEvent.click(screen.getByRole('button', { name: 'Tạo lớp' }))
    await waitFor(() => expect(service.createClassroom).toHaveBeenCalledWith('c1', { name: 'Lớp sáng' }))
    await waitFor(() => expect(screen.getByLabelText('Mở đăng ký')).toBeEnabled())
    await userEvent.click(screen.getByLabelText('Mở đăng ký'))
    expect(service.updateClassroom).toHaveBeenCalledWith('c1', 'room1', { is_join_enabled: false })
  })
  it('opens the roster of a specific class and returns to classroom management', async () => {
    render(<TeacherEnrollmentPanel course={course} onMembersChanged={vi.fn()} />)
    await userEvent.click(await screen.findByRole('button', { name: 'Học viên lớp Lớp tối' }))
    expect(await screen.findByText('Chưa có học viên ở trạng thái này.')).toBeVisible()
    expect(service.listClassroomEnrollments).toHaveBeenCalledWith('c1', 'room1', 'ACTIVE', expect.any(AbortSignal))
    await userEvent.click(screen.getByRole('button', { name: 'Danh sách lớp học' }))
    expect(screen.getByRole('button', { name: 'Học viên lớp Lớp tối' })).toBeVisible()
  })
})
