# Generated by Django 5.2.18 on 2026-10-08 09:05

import apps.courses.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def retire_invitations(apps, schema_editor):
    Member = apps.get_model("courses", "CourseMember")
    Member.objects.using(schema_editor.connection.alias).filter(status="INVITED").update(
        status="REMOVED", removed_at=django.utils.timezone.now()
    )


def bootstrap_enrollment(apps, schema_editor):
    alias = schema_editor.connection.alias
    Course = apps.get_model("courses", "Course")
    Policy = apps.get_model("courses", "AccessPolicy")
    Classroom = apps.get_model("courses", "Classroom")
    Member = apps.get_model("courses", "CourseMember")
    Profile = apps.get_model("users", "StudentProfile")
    Enrollment = apps.get_model("courses", "Enrollment")
    for course in Course.objects.using(alias).all().iterator():
        Policy.objects.using(alias).get_or_create(course_id=course.pk)
        classroom = Classroom.objects.using(alias).create(course_id=course.pk, name=course.title)
        for member in Member.objects.using(alias).filter(course_id=course.pk, role="STUDENT", user__role="STUDENT").iterator():
            profile, _ = Profile.objects.using(alias).get_or_create(user_id=member.user_id)
            Enrollment.objects.using(alias).create(
                classroom_id=classroom.pk, student_id=profile.pk,
                status="ACTIVE" if member.status == "ACTIVE" else "WITHDRAWN",
                enrolled_at=member.joined_at,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_single_course_owner'),
        ('users', '0003_role_specific_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PRIVATE', max_length=7)),
                ('access_type', models.CharField(choices=[('FREE', 'Free'), ('PAID', 'Paid')], default='FREE', max_length=4)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('require_class_code', models.BooleanField(default=True)),
                ('require_approval', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('class_code', models.CharField(default=apps.courses.models.generate_class_code, editable=False, max_length=12, unique=True)),
                ('is_join_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn')], default='ACTIVE', max_length=10)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('progress_percent', models.FloatField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELED', 'Canceled')], default='PENDING', max_length=8)),
                ('message', models.TextField(blank=True, default='')),
                ('review_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='coursemember',
            name='courses_valid_member_status',
        ),
        migrations.RunPython(retire_invitations, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='coursemember',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='coursemember',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'SUSPENDED', 'REMOVED'])), name='courses_valid_member_status'),
        ),
        migrations.AddField(
            model_name='accesspolicy',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_policy', to='courses.course'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='courses.course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.classroom'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='courses.classroom'),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='accesspolicy',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('access_type', 'FREE'), ('price', 0)), models.Q(('access_type', 'PAID'), ('price__gt', 0)), _connector='OR'), name='courses_valid_access_price'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('classroom', 'student'), name='courses_unique_class_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'COMPLETED', 'WITHDRAWN'])), name='courses_valid_enrollment_status'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percent__gte', 0), ('progress_percent__lte', 100)), name='courses_valid_progress'),
        ),
        migrations.AddConstraint(
            model_name='joinrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('classroom', 'student'), name='courses_one_pending_join_request'),
        ),
        migrations.AddConstraint(
            model_name='joinrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED', 'REJECTED', 'CANCELED'])), name='courses_valid_join_status'),
        ),
        migrations.AddConstraint(
            model_name='joinrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reviewed_at__isnull', True), ('reviewed_by__isnull', True), ('status__in', ['PENDING', 'CANCELED'])), models.Q(('reviewed_at__isnull', False), ('reviewed_by__isnull', False), ('status__in', ['APPROVED', 'REJECTED'])), _connector='OR'), name='courses_valid_join_review'),
        ),
        migrations.RunPython(bootstrap_enrollment, migrations.RunPython.noop),
    ]
