# Generated by Django 5.2.18 on 2026-10-09 15:10

import apps.courses.announcement_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_classroomsession_title_classroomannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomannouncement',
            name='image',
            field=models.FileField(blank=True, default='', storage=apps.courses.announcement_storage.announcement_storage, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='classroomannouncement',
            name='image_content_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='classroomannouncement',
            name='link',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
