# Generated by Django 5.2.18 on 2026-10-09 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_classroomsession'),
        ('documents', '0002_documentversion_watermarked_sha256_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='courses.classroomsession'),
        ),
    ]
